# -*- coding: utf-8 -*-
"""Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzXZSa8rVK6v8au5wQGw3_qQbKSnskHv
"""

# Question 1, Creating a function
def calculate_discount(price, discount_percent):
  if discount_percent >= 20:
    discount_amount = (discount_percent / 100) * price
    final_price = price - discount_amount
    return final_price

  else:
    return price

calculate_discount(100, 35)

# Question 2, prompting
price = float(input("Enter the original price of the item:"))
discount_percentage = float(input("Enter the discount percentage:"))
final_price = calculate_discount(price, discount_percentage)
print(f"The final price after the discount is: {final_price}")





